title: Vox Gaukas
email: i@gaukas.wang
description: >- # this means to ignore newlines until "baseurl:"
  A place for me to reflect, meditate, learn, and share my thoughts and experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "vox.gaukas.wang" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /posts/:title.html
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# twitter_username: jekyllrb
# github_username:  gaukas

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:i@gaukas.wang"}
  - {title: "Portfolio", icon: "user", url: "https://gaukas.wang"}
  - {title: "DocHive", icon: "book", url: "https://dochive.gaukas.wang"}
  - {title: Github, icon: github, url: "https://github.com/gaukas/vox.gaukas.wang"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

# Build settings
# theme: minima
# remote_theme: https://github.com/niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-feed
  # - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
